# SPDX-License-Identifier: GPL-2.0
all:

TEST_GEN_FILES := swap_offload workingset_offload
TEST_PROGS := zram.sh zram03.sh zram04.sh
TEST_FILES := zram01.sh zram02.sh zram_lib.sh
EXTRA_CLEAN := err.log

include ../lib.mk
